---
- hosts: all 
  gather_facts: no
  become: yes
  become_method: sudo
  tasks:
    - name: updating all hosts 
      apt:
        update_cache: yes
    - name : sudo wait
      become: yes
      shell: while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;

- hosts: dev 
  become: true
  become_method: sudo
  gather_facts: no
  tasks:
    - name: update all dev 
      apt:
        update_cache: true

    - name: Installing nginx
      apt:
        name: nginx
        state: latest
        update_cache: true

    - name: pip install
      apt:
        name: python3-pip
        state: latest
        update_cache: true

    - name: Installing flask app
      pip:
        executable: pip3
        name: flask
        state: latest

    - name: apt update
      apt:
        update_cache: true

    - name: Installing flask service deployment
      pip:
        executable: pip3
        name: gunicorn
        state: latest

    - name: apt update
      apt:
        update_cache: true

    - name: copy flask app 
      copy:
        src: service.py
        dest: /home/ubuntu/app.py
        owner: ubuntu
        mode: '0644'

    - name: deploying Flask application 
      shell: gunicorn -w 2 -D -b 0.0.0.0:5000 app:app

    - name: install snmpd 
      apt:
        name: snmpd
        state: latest
        update_cache: true

    - name: configure snmpd
      template:
        src: snmpd.conf.j2
        dest: /etc/snmp/snmpd.conf
        owner: root
        group: root
        mode: '0644'
      notify: restart snmpd

    - name: apt update
      apt:
        update_cache: true

  handlers:
    - name: restart snmpd
      service:
        name: snmpd
        state: restarted
  
- hosts: all
  gather_facts: true
    
- hosts: HAproxy
  become: true
  tasks: 

    - name: Installing HAPROXY
      apt:
        name: haproxy
        state: present
        update_cache: true
   
    - name: Installing keepalived
      apt:
        name: keepalived
        state: present
        update_cache: true
    
    - name: Template keepalived config
      template:
        src: ./templates/keepalived.conf.j2
        dest: /etc/keepalived/keepalived.conf
        owner: root
        group: root
        mode: '0644'

    - name: Restart haproxy
      service:
        name: haproxy
        state: restarted

    - name: Installing Nginx
      apt:
        name: nginx
        state: latest

    - name: Installing snmp, snmp-mibs-downloader
      apt: 
        name: [ 'snmp', 'snmp-mibs-downloader' ] 
        state: latest


    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

    - name: Restart keepalived
      service:
        name: keepalived
        state: restarted


